name: OnlineList
version: 1.00
author: Trsak
main: cz.trsak.onlinelist.Main
depend: [Vault]
description: A plugin that enables custom achievements and RP books on your server.
permissions:
  onlinelist.use:
    description: Allows to use /list command.
    default: true
  onlinelist.reload:
    description: Allows to use /listreload command.
    default: false
commands:
  list:
    description: List all online players with groups.
  listreload:
    description: Reload OnlineList config.