#Config
PlayersDivider: ", "
AfterGroups: "&f: "

#Groups Aliases
Aliases:
  default: "Users"

#Groups Sorting (From First to last, unlisted groups will be after those)
GroupSort:
  - Owner
  - Admin
  - default

#Prefixes
PlayersPrefix: "&6"
PlayersSufix: ""
GroupsPrefix: "&6"
GroupsSufix: "&f"

#Messages
PermissionsError: "&4You don't have permission to do that!"
PlayersOnline: "&6Players online (%players_online%):"
ConfigReload: "&2Config was successfully reloaded."